{
  "INTERNAL_SERVER_ERROR": "Đã có lỗi xảy ra, vui lòng thử lại sau",
  "SUCCESS": "Thành công"
}
